Repository zzzprojects/System.Linq.Dynamic.Core, pull requests merged in 2021-12, with the labels that each got.

#554 Support for parsing Binary Integer
  System.Linq.Dynamic.Core.sln
  src/Microsoft.EntityFrameworkCore.DynamicLinq.EFCore5/Microsoft.EntityFrameworkCore.DynamicLinq.EFCore5.csproj
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Parser/NumberParser.cs
  src/System.Linq.Dynamic.Core/Res.cs
  src/System.Linq.Dynamic.Core/System.Linq.Dynamic.Core.csproj
  src/System.Linq.Dynamic.Core/Tokenizer/TextParser.cs
  test/System.Linq.Dynamic.Core.Tests/EntitiesTests.AverageAsync.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/NumberParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/System.Linq.Dynamic.Core.Tests.csproj
Labels: feature

#558 Allow assembly to be collected
  src/System.Linq.Dynamic.Core/DynamicClassFactory.cs
Labels: bug

#561 Fix NET35 build + add unit test for OrderBy with IComparer
  src/System.Linq.Dynamic.Core/DynamicClassFactory.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs
Labels: bug

#562 Make TextParser public
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Tokenizer/TextParser.cs
  src/System.Linq.Dynamic.Core/Tokenizer/Token.cs
  src/System.Linq.Dynamic.Core/Tokenizer/TokenId.cs
Labels: feature

#563 GitHub Actions: use actions/checkout@v2
  .github/workflows/ci.yml
Labels: security
