Repository zzzprojects/System.Linq.Dynamic.Core, pull requests merged in 2024-02, with the labels that each got.

#770 Enhancements to SlidingCache<> for Improved Thread Safety and Performance
  src/System.Linq.Dynamic.Core/Util/Cache/CacheConfig.cs
  src/System.Linq.Dynamic.Core/Util/Cache/SlidingCache.cs
  test/System.Linq.Dynamic.Core.Tests/Util/Cache/SlidingCacheTests.cs
Labels: feature

#780 Add RadzenDataGrid.BlazorApp example
  System.Linq.Dynamic.Core.sln
  src-blazor/RadzenDataGrid.BlazorApp/Components/App.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Layout/MainLayout.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Layout/MainLayout.razor.css
  src-blazor/RadzenDataGrid.BlazorApp/Components/Layout/NavMenu.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Layout/NavMenu.razor.css
  src-blazor/RadzenDataGrid.BlazorApp/Components/Pages/Counter.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Pages/Error.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Pages/Home.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Pages/Home.razor.css
  src-blazor/RadzenDataGrid.BlazorApp/Components/Pages/Weather.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/Routes.razor
  src-blazor/RadzenDataGrid.BlazorApp/Components/_Imports.razor
  src-blazor/RadzenDataGrid.BlazorApp/Entities/PriceListService.cs
  src-blazor/RadzenDataGrid.BlazorApp/Entities/PriceListServiceBase.cs
  src-blazor/RadzenDataGrid.BlazorApp/MyDbContext.cs
  src-blazor/RadzenDataGrid.BlazorApp/Program.cs
  src-blazor/RadzenDataGrid.BlazorApp/Properties/launchSettings.json
  src-blazor/RadzenDataGrid.BlazorApp/RadzenDataGrid.BlazorApp.csproj
  src-blazor/RadzenDataGrid.BlazorApp/appsettings.Development.json
  src-blazor/RadzenDataGrid.BlazorApp/appsettings.json
  src-blazor/RadzenDataGrid.BlazorApp/wwwroot/app.css
  src-blazor/RadzenDataGrid.BlazorApp/wwwroot/bootstrap/bootstrap.min.css
  src-blazor/RadzenDataGrid.BlazorApp/wwwroot/bootstrap/bootstrap.min.css.map
  src-blazor/RadzenDataGrid.BlazorApp/wwwroot/favicon.png
Labels: test

#774 Fixed calling property on nested static class
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Parser/ExpressionPromoter.cs
  src/System.Linq.Dynamic.Core/Parser/TypeHelper.cs
  test/System.Linq.Dynamic.Core.Tests/DynamicExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/Helpers/Models/User.cs
  test/System.Linq.Dynamic.Core.Tests/Helpers/Models/UserInfo.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/TypeHelperTests.cs
  test/System.Linq.Dynamic.Core.Tests/TestClasses/StaticHelper.cs
  test/System.Linq.Dynamic.Core.Tests/TestClasses/TestCustomTypeProvider.cs
  test/System.Linq.Dynamic.Core.Tests/Util/Cache/SlidingCacheTests.cs
Labels: bug
