Repository zzzprojects/System.Linq.Dynamic.Core, pull requests merged in 2025-01, with the labels that each got.

#866 Refactor KeywordsHelper, TypeFinder and update comments on ParsingConfig
  src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs
  src/System.Linq.Dynamic.Core/Exceptions/ParseException.cs
  src/System.Linq.Dynamic.Core/Extensions/ListExtensions.cs
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Parser/ExpressionPromoter.cs
  src/System.Linq.Dynamic.Core/Parser/IExpressionPromoter.cs
  src/System.Linq.Dynamic.Core/Parser/IKeywordsHelper.cs
  src/System.Linq.Dynamic.Core/Parser/ITypeFinder.cs
  src/System.Linq.Dynamic.Core/Parser/KeywordsHelper.cs
  src/System.Linq.Dynamic.Core/Parser/TypeFinder.cs
  src/System.Linq.Dynamic.Core/ParsingConfig.cs
  src/System.Linq.Dynamic.Core/Tokenizer/TextParser.cs
  test/System.Linq.Dynamic.Core.Tests/EntitiesTests.cs
  test/System.Linq.Dynamic.Core.Tests/Helpers/Entities/BlogContext.cs
  test/System.Linq.Dynamic.Core.Tests/Helpers/Entities/Post.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionPromoterTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/TypeFinderTests.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Where.cs
Labels: refactor

#870 Fix CVE-2024-51417
  src/System.Linq.Dynamic.Core/CustomTypeProviders/AbstractDynamicLinqCustomTypeProvider.cs
  src/System.Linq.Dynamic.Core/CustomTypeProviders/DefaultDynamicLinqCustomTypeProvider.cs
  src/System.Linq.Dynamic.Core/CustomTypeProviders/IDynamicLinkCustomTypeProvider.cs
  src/System.Linq.Dynamic.Core/Extensions/LinqExtensions.cs
  src/System.Linq.Dynamic.Core/Parser/PredefinedTypesHelper.cs
  src/System.Linq.Dynamic.Core/ParsingConfig.cs
  test/System.Linq.Dynamic.Core.Tests/CustomTypeProviders/DefaultDynamicLinqCustomTypeProviderTests.cs
  test/System.Linq.Dynamic.Core.Tests/DynamicClassTest.cs
  test/System.Linq.Dynamic.Core.Tests/DynamicExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/Entities/Worker.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/Helpers/Models/AppSettings.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/MethodFinderTest.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Is,OfType,As,Cast.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Select.cs
  test/System.Linq.Dynamic.Core.Tests/SecurityTests.cs
  test/System.Linq.Dynamic.Core.Tests/TestClasses/TestCustomTypeProvider.cs
Labels: bug

#874 Fix calling static properties or fields in non-static class
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.MemberAccess.cs
  test/System.Linq.Dynamic.Core.Tests/SecurityTests.cs
Labels: bug

#879 Change internal usage from obsolete IDynamicLinkCustomTypeProvider to IDynamicLinqCustomTypeProvider
  src-console/ConsoleAppEF2.0.2_InMemory/Program.cs
  src-console/ConsoleAppEF2.0/Program.cs
  src-console/ConsoleAppEF2.1.1/Program.cs
  src-console/ConsoleAppEF2.1/Program.cs
  src/System.Linq.Dynamic.Core/CustomTypeProviders/DefaultDynamicLinqCustomTypeProvider.cs
  src/System.Linq.Dynamic.Core/ParsingConfig.cs
  test-xamarin/WindowsUniversalTestApp14393/WindowsAppCustomTypeProvider.cs
  test-xamarin/WindowsUniversalTestApp16299/WindowsAppCustomTypeProvider.cs
  test/System.Linq.Dynamic.Core.Tests/DynamicExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.MethodCall.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionPromoterTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/TypeFinderTests.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Methods.cs
  test/System.Linq.Dynamic.Core.Tests/TestClasses/TestCustomTypeProvider.cs
Labels: feature

#875 Add option to ParsingConfig to allow the Equals and ToString methods on object
  src-blazor/BlazorAppServer/BlazorAppServer.csproj
  src/System.Linq.Dynamic.Core/Compatibility/TypeExtensions.cs
  src/System.Linq.Dynamic.Core/DynamicClassFactory.cs
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Parser/PredefinedMethodsHelper.cs
  src/System.Linq.Dynamic.Core/ParsingConfig.cs
  src/System.Linq.Dynamic.Core/Res.cs
  test/System.Linq.Dynamic.Core.Tests/DynamicClassTest.cs
  test/System.Linq.Dynamic.Core.Tests/DynamicExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/MethodFinderTest.cs
  test/System.Linq.Dynamic.Core.Tests/SecurityTests.cs
Labels: feature

#882 ExpressionParser: add 2nd ctor with an extra non-optional parameter
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
Labels: feature

#876 Update and Fix SecurityTests
  test/System.Linq.Dynamic.Core.Tests/Helpers/Models/AppSettings.cs
  test/System.Linq.Dynamic.Core.Tests/SecurityTests.cs
Labels: test

#883 Fix the usage of ParsingConfig in some methods in the DynamicQueryableExtensions class
  src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.MemberAccess.cs
Labels: bug

#884 By default the RestrictOrderByToPropertyOrField is now set to true in the ParsingConfig
  README.md
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Parser/IKeywordsHelper.cs
  src/System.Linq.Dynamic.Core/Parser/KeywordsHelper.cs
  src/System.Linq.Dynamic.Core/ParsingConfig.cs
  test/System.Linq.Dynamic.Core.Tests/EntitiesTests.OrderBy.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderByDescending.cs
Labels: feature
