Repository zzzprojects/System.Linq.Dynamic.Core, pull requests merged in 2025-05, with the labels that each got.

#922 Update DynamicGetMemberBinder to only add BindingRestrictions for dynamic type and cache the DynamicMetaObject
  System.Linq.Dynamic.Core.sln
  src-console/ConsoleAppPerformanceTest/ConsoleAppPerformanceTest.csproj
  src-console/ConsoleAppPerformanceTest/Program.cs
  src/System.Linq.Dynamic.Core/DynamicGetMemberBinder.cs
Labels: bug

#923 Fix MethodFinder TryFindAggregateMethod to support array
  src/System.Linq.Dynamic.Core/Parser/SupportedMethods/MethodFinder.cs
  src/System.Linq.Dynamic.Core/Parser/TypeHelper.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.Sum.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.Sum.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Sum.cs
Labels: bug

#915 Add support for "not in" and "not_in"
  src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs
  src/System.Linq.Dynamic.Core/Tokenizer/TextParser.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.cs
Labels: feature

#925 Add extra unittests for NullPropagation / ToString / AllowEqualsAndToStringMethodsOnObject is true
  src/System.Linq.Dynamic.Core/Parser/ExpressionHelper.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionParserTests.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Where.cs
Labels: test

#926 Add validation when passing ParsingConfig in args
  src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs
  src/System.Linq.Dynamic.Core/Validation/Check.cs
  test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs
  test/System.Linq.Dynamic.Core.Tests/QueryableTests.Where.cs
Labels: feature

#905 Fix: Add Fallback in ExpressionPromoter to Handle Cache Cleanup in ConstantExpressionHelper
  src/System.Linq.Dynamic.Core/Parser/ExpressionPromoter.cs
  test/System.Linq.Dynamic.Core.Tests/Parser/ExpressionPromoterTests.cs
Labels: bug
